In [1]:
import pandas as pd

In [2]:
apt_s1 = pd.read_csv('Distinct_APT_s1_correlation_matrix.csv')
apt_s2 = pd.read_csv('Distinct_APT_s2_correlation_matrix.csv')
apt_s1

,Unnamed: 0,v1,v2,v3,v4,zr,a,ndt1,ndt2,ndt3,ndt4,sndt,alpha,mean_log_rt,alpha_arc_box,acc_arc_box
0,v1,NaN,0.811411,-0.552538,-0.572278,-0.472533,0.088523,0.017366,-0.014895,0.138517,0.099597,-0.264301,0.359239,-0.258663,0.337750,0.590433
1,v2,0.811411,NaN,-0.586018,-0.550648,-0.518992,0.302157,-0.041346,0.037140,0.205080,0.165615,-0.268570,0.508406,-0.062546,0.486768,0.729768
2,v3,-0.552538,-0.586018,NaN,0.852226,0.060542,-0.172219,-0.042138,-0.108154,-0.129189,-0.075202,0.183222,-0.353092,0.159223,-0.334871,-0.647848
3,v4,-0.572278,-0.550648,0.852226,NaN,-0.009488,-0.125108,-0.020985,-0.088236,-0.038042,-0.115834,0.185299,-0.295659,0.243072,-0.304832,-0.578578
4,zr,-0.472533,-0.518992,0.060542,-0.009488,NaN,-0.255368,0.009348,0.048264,-0.447354,-0.436386,0.088278,-0.451065,-0.179669,-0.454728,-0.422107
5,a,0.088523,0.302157,-0.172219,-0.125108,-0.255368,NaN,0.114676,0.116802,0.298970,0.299719,-0.254742,0.647210,0.841234,0.695112,0.754255
6,ndt1,0.017366,-0.041346,-0.042138,-0.020985,0.009348,0.114676,NaN,0.890822,0.709826,0.713064,0.177444,0.155373,0.442477,0.141851,0.055056
7,ndt2,-0.014895,0.037140,-0.108154,-0.088236,0.048264,0.116802,0.890822,NaN,0.691055,0.675371,0.231846,0.150956,0.421089,0.112560,0.070279
8,ndt3,0.138517,0.205080,-0.129189,-0.038042,-0.447354,0.298970,0.709826,0.691055,NaN,0.903214,0.170995,0.442722,0.598858,0.371873,0.309231
9,ndt4,0.099597,0.165615,-0.075202,-0.115834,-0.436386,0.299719,0.713064,0.675371,0.903214,NaN,0.124221,0.421547,0.608730,0.398752,0.316315
10,sndt,-0.264301,-0.268570,0.183222,0.185299,0.088278,-0.254742,0.177444,0.231846,0.170995,0.124221,NaN,-0.481944,-0.002515,-0.511715,-0.412662
11,alpha,0.359239,0.508406,-0.353092,-0.295659,-0.451065,0.647210,0.155373,0.150956,0.442722,0.421547,-0.481944,NaN,0.460286,0.945365,0.721116
12,mean_log_rt,-0.258663,-0.062546,0.159223,0.243072,-0.179669,0.841234,0.442477,0.421089,0.598858,0.608730,-0.002515,0.460286,NaN,0.485613,0.417856
13,alpha_arc_box,0.337750,0.486768,-0.334871,-0.304832,-0.454728,0.695112,0.141851,0.112560,0.371873,0.398752,-0.511715,0.945365,0.485613,NaN,0.773897
14,acc_arc_box,0.590433,0.729768,-0.647848,-0.578578,-0.422107,0.754255,0.055056,0.070279,0.309231,0.316315,-0.412662,0.721116,0.417856,0.773897,NaN

In [3]:
sum=apt_s1+apt_s2
sum['Unnamed: 0'] = apt_s1['Unnamed: 0']
ave=sum.loc[:,sum.columns != 'Unnamed: 0']/2
idx = 0 
ave.insert(loc=idx, column='par', value=apt_s1['Unnamed: 0'])

In [4]:
ave

,par,v1,v2,v3,v4,zr,a,ndt1,ndt2,ndt3,ndt4,sndt,alpha,mean_log_rt,alpha_arc_box,acc_arc_box
0,v1,NaN,0.831436,-0.586615,-0.611592,-0.409813,0.162048,0.009615,0.011948,0.135983,0.118409,-0.360703,0.402294,-0.209392,0.370939,0.627851
1,v2,0.831436,NaN,-0.614521,-0.599041,-0.454772,0.338060,-0.036019,0.067485,0.169762,0.156113,-0.417295,0.500613,-0.047791,0.476875,0.744508
2,v3,-0.586615,-0.614521,NaN,0.838116,-0.019944,-0.201095,-0.055429,-0.155217,-0.131084,-0.072610,0.313750,-0.367045,0.145025,-0.363798,-0.646446
3,v4,-0.611592,-0.599041,0.838116,NaN,-0.056566,-0.199528,-0.046332,-0.146069,-0.048288,-0.139742,0.268535,-0.329966,0.172931,-0.337732,-0.623896
4,zr,-0.409813,-0.454772,-0.019944,-0.056566,NaN,-0.229216,0.040504,0.082553,-0.315699,-0.323541,0.181438,-0.416795,-0.158124,-0.406440,-0.331013
5,a,0.162048,0.338060,-0.201095,-0.199528,-0.229216,NaN,0.154094,0.155534,0.315641,0.325249,-0.325277,0.656608,0.816866,0.709122,0.782994
6,ndt1,0.009615,-0.036019,-0.055429,-0.046332,0.040504,0.154094,NaN,0.892586,0.749349,0.741560,0.219104,0.139984,0.480727,0.103893,0.074671
7,ndt2,0.011948,0.067485,-0.155217,-0.146069,0.082553,0.155534,0.892586,NaN,0.729552,0.704709,0.220523,0.130206,0.476997,0.088704,0.130919
8,ndt3,0.135983,0.169762,-0.131084,-0.048288,-0.315699,0.315641,0.749349,0.729552,NaN,0.907842,0.121687,0.347352,0.620983,0.304732,0.281089
9,ndt4,0.118409,0.156113,-0.072610,-0.139742,-0.323541,0.325249,0.741560,0.704709,0.907842,NaN,0.108138,0.356680,0.627780,0.339692,0.297629
10,sndt,-0.360703,-0.417295,0.313750,0.268535,0.181438,-0.325277,0.219104,0.220523,0.121687,0.108138,NaN,-0.482832,-0.013979,-0.524593,-0.499336
11,alpha,0.402294,0.500613,-0.367045,-0.329966,-0.416795,0.656608,0.139984,0.130206,0.347352,0.356680,-0.482832,NaN,0.432117,0.950004,0.711088
12,mean_log_rt,-0.209392,-0.047791,0.145025,0.172931,-0.158124,0.816866,0.480727,0.476997,0.620983,0.627780,-0.013979,0.432117,NaN,0.467317,0.412836
13,alpha_arc_box,0.370939,0.476875,-0.363798,-0.337732,-0.406440,0.709122,0.103893,0.088704,0.304732,0.339692,-0.524593,0.950004,0.467317,NaN,0.763055
14,acc_arc_box,0.627851,0.744508,-0.646446,-0.623896,-0.331013,0.782994,0.074671,0.130919,0.281089,0.297629,-0.499336,0.711088,0.412836,0.763055,NaN

In [5]:
ave = ave.fillna(1)
ave= ave.round(3)

ave.to_csv('Study_2_average_distinct_correlation_across_2_data.csv')